name: Build

on:
  push:
    branches: [ "develop-4.4" ]
#  pull_request:
#    branches: [ "develop-4.4" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download gcc
      run: | 
        wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
        sudo tar xvf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz  -C /usr/local/
    
    - name: Set environment
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=/usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-

    - name: Set RockChip kernel
      run: make rockchip_linux_defconfig

    - name: make
      run: exports; make -j8
    
