name: Build

on:
  push:
    branches: [ "release-4.4-rockpi4" ]
#  pull_request:
#    branches: [ "develop-4.4" ]

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      ARCH: arm64
      CROSS_COMPILE: "/usr/local/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-"
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

    steps:
    - name: Upload Release Assets
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GH_TOKEN}}
        script: |
          const fs = require('fs').promises;
          const { repo: { owner, repo }, sha } = context;
          const release_id = 88294537; // "Unreleased"

          const listExistingArtifacts = (await github.repos.listReleaseAssets({
            owner,
            repo,
            release_id,
          })).data;

          const sixMonth = 6 * 30 * 24 * 60 * 60 * 1000;
          // Csak tesztre
          const oneHour = 60 * 60 * 1000;

          //let oldAssets = listExistingArtifacts.find(item =>  (new Date(item.created_at).getTime()+oneHour>= new Date().getTime()));
          let oldAssets = listExistingArtifacts;
          console.log("Old Assets size:", oldAssets.length);

          for (let a of oldAssets) {
            console.log("-----------------------")
            console.log("Name: ", a.name);
            console.log("Created:", a.created_at);
            console.log("Noew:", new Date().getTime());
            console.log("OLD?:",  (new Date(item.created_at).getTime()+oneHour>= new Date().getTime()));
            console.log("-----------------------")
          }

          console.log("Done.");    